### ISSUE TITLE
AttributeError: module 'torchvision.models.detection._utils' has no attribute 'smooth_l1_loss'

### ISSUE THREAD

**Issue by Qi-Chuan** [pranoyr/large-scale-visual-relationship-understanding#1]
Hi, I have a problem to run this code. When I run "train_large_scale.py", it occurs that:
     AttributeError: module 'torchvision.models.detection._utils' has no attribute 'smooth_l1_loss'
It seems that torchvision has a problem.
My environment is:  Linux 
                                 torch 1.4.0
                                 torchvision 0.5.0

In addition, could you please tell us the requirements and the package versions of this repository? Thanks a lot!

**Comment by pranoyr** [comment]
My Version

torch                     1.7.1
torchvision               0.8.2

**Comment by Qi-Chuan** [comment]
Thanks for reply, I will reinstall the new environment and try to run the code!

**Comment by pranoyr** [comment]
I have updated the code in master branch. Please make sure you run the latest version.
